site_name: IT-sikkerhed - Mickey
repo_url: https://github.com/mickeygeecom/its

nav:
  - Start: index.md
  - Fagets læringsmål: læringsmål/faget.md
  - Målsætning: læringsmål/målsætning.md
  - Infrastruktur:
    - Arkitektur Overblik: infrastruktur/architecture.md
    - Network Diagram: infrastruktur/network_diagram.md
  - Mindmap: mindmap.md
  - Roadmap:
    - P1 - Research: roadmap/fase1.md
    - P2 - Detection og analyse: roadmap/fase2.md
    - P3 - Inddæmning, eradication og recovery: roadmap/fase3.md
    - P4 - Lessons learned og dokumentation: roadmap/fase4.md
  - Kilder: sources.md
  - Logbog:
    - 19 feb.: log/19022025.md
    - 14-15 apr.: log/15042025.md

theme:
  name: material
  #features:
  #  - mermaid

plugins:
- search
- mermaid2